In [1]:
#import tensorflow
import tensorflow  as tf
print(tf.__version__)

2.15.0


In [2]:
#create a tensor
scaler=tf.constant(9)
scaler


<tf.Tensor: shape=(), dtype=int32, numpy=9>

In [3]:
#check the no of dimenstion
scaler.ndim

0

In [4]:
#create a vector
vec=tf.constant([[10,10],[10,10]],dtype=tf.float16)
vec

<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[10., 10.],
       [10., 10.]], dtype=float16)>

tf.variable

In [5]:
var=tf.Variable([[20,7],
              [12,12]])

In [6]:
#change the var
var[[0]].assign(15)
var

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[15, 15],
       [12, 12]], dtype=int32)>

In [7]:
#creating random tensors
ran=tf.random.Generator.from_seed(42)
ran.normal(shape=(2,5))

<tf.Tensor: shape=(2, 5), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702,  0.07595026, -1.2573844 , -0.23193765],
       [-1.8107855 ,  0.09988727, -0.50998646, -0.7535806 , -0.5716629 ]],
      dtype=float32)>

In [8]:
ran

In [9]:
not_shuffe=tf.constant([[100,100],[19,182]],dtype=float)

In [10]:
not_shuffe

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[100., 100.],
       [ 19., 182.]], dtype=float32)>

In [11]:
tf.random.shuffle(not_shuffe,seed=45)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 19., 182.],
       [100., 100.]], dtype=float32)>

In [12]:
tf.random.set_seed(42)#global seed
tf.random.shuffle(not_shuffe,seed=6)#operration seed


<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[100., 100.],
       [ 19., 182.]], dtype=float32)>

In [13]:
#creating tensors usign numpy
tf.zeros([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [14]:
#creating tensors usign numpy
tf.zeros(shape=(2,4))

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [15]:
#numpy array into tensors
import numpy as np
numpy_a=np.arange(1,25,dtype=np.int32)

In [16]:
numpy_a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [17]:
 tensor=tf.constant(numpy_a,shape=(2,3,4))

In [18]:
tensor

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

In [19]:
#gettign info from tensors
tensor.ndim

3

# we can get the
#shape
#rank
#axis or dim
#size


In [20]:
rank_tense=tf.ones([2,3,4,5])
rank_tense[0][0]

<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]], dtype=float32)>

In [21]:
tf.size(rank_tense)

<tf.Tensor: shape=(), dtype=int32, numpy=120>

indexing tensors

In [22]:
rank_tense[:,:1,:1,:1]

<tf.Tensor: shape=(2, 1, 1, 1), dtype=float32, numpy=
array([[[[1.]]],


       [[[1.]]]], dtype=float32)>

In [23]:
 rank_2=tf.constant([[10,9],
                     [3,5]])

In [24]:
rank_2[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([9, 5], dtype=int32)>

In [25]:
rank_3=rank_2[...,tf.newaxis]

In [26]:
rank_3.shape

TensorShape([2, 2, 1])

In [27]:
rank_3=tf.expand_dims(rank_2,axis=1)
rank_3.shape

TensorShape([2, 1, 2])

In [28]:
#manipulating tensors
tensor_2=tf.constant([[10,7],[2,4]])

In [29]:
tensor_2 +10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [12, 14]], dtype=int32)>

In [30]:
tf.multiply(tensor_2,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 20,  40]], dtype=int32)>

In [31]:
#matrix Multiplication
tf.matmul(tensor_2,tensor_2)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[114,  98],
       [ 28,  30]], dtype=int32)>

In [32]:
tensor_2* tensor_2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  49],
       [  4,  16]], dtype=int32)>

In [33]:
X=tf.constant([[10,7],[4,5],[9,5]])
Y=tf.constant([[3,4,9],[7,9,5]])

In [34]:
X.shape

TensorShape([3, 2])

In [35]:
tf.matmul(X,tf.reshape(Y,shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 79, 103, 125],
       [ 47,  61,  61],
       [ 62,  81, 106]], dtype=int32)>

In [36]:
tf.matmul(tf.transpose(X),tf.transpose(Y))

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[127, 151],
       [ 86, 119]], dtype=int32)>

In [37]:
#tf.dotproduct()
tf.tensordot(X,Y,axes=1)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 79, 103, 125],
       [ 47,  61,  61],
       [ 62,  81, 106]], dtype=int32)>

In [38]:
#changinig dtype of tensors
tensor_3=tf.constant([[2.,3.],[9.,6.]])
tensor_3.dtype

tf.float32

In [39]:
#use cast for the  changing dtype
tensor_3=tf.cast(tensor_3,dtype=tf.int16)

In [40]:
tensor_3.dtype

tf.int16

Aggregation tensors

In [41]:
#get abs values
D=tf.constant([-7,10])

In [42]:
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

In [43]:
E=tf.constant(np.random.randint(0,100,size=100))

In [44]:
#find minimum
tf.reduce_min(D)

<tf.Tensor: shape=(), dtype=int32, numpy=-7>

In [45]:
tf.reduce_max(D)


<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [46]:
import tensorflow_probability as tfp

In [47]:
tfp.stats.variance(D)

<tf.Tensor: shape=(), dtype=int32, numpy=72>

In [48]:
tf.math.reduce_std(tf.cast(D,dtype=tf.float16))

<tf.Tensor: shape=(), dtype=float16, numpy=8.5>

In [49]:
tf.math.reduce_variance(tf.cast(D,dtype=tf.float16))

<tf.Tensor: shape=(), dtype=float16, numpy=72.25>

In [50]:
#finding positional maximum and minimum
F=tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [51]:
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [52]:
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [53]:
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

In [54]:
tf.reduce_min(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

In [55]:
# tf.random.set_seed(42)

In [56]:
G=tf.constant(tf.random.uniform(shape=[50]),shape=(1,1,1,1,50))

In [57]:
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.68789124, 0.48447883, 0.9309944 , 0.252187  , 0.73115396,
           0.89256823, 0.94674826, 0.7493341 , 0.34925628, 0.54718256,
           0.26160395, 0.69734323, 0.11962581, 0.53484344, 0.7148968 ,
           0.87501776, 0.33967495, 0.17377627, 0.4418521 , 0.9008261 ,
           0.13803864, 0.12217975, 0.5754491 , 0.9417181 , 0.9186585 ,
           0.59708476, 0.6109482 , 0.82086265, 0.83269787, 0.8915849 ,
           0.01377225, 0.49807465, 0.57503664, 0.6856195 , 0.75972784,
           0.908944  , 0.40900218, 0.8765154 , 0.53890026, 0.42733097,
           0.401173  , 0.66623247, 0.16348064, 0.18220246, 0.97040176,
           0.06139731, 0.53034747, 0.9869994 , 0.4746945 , 0.8646754 ]]]]],
      dtype=float32)>

In [58]:
G_s=tf.squeeze(G)

In [59]:
G_s.shape

TensorShape([50])

One hot encoding in TF

In [60]:
li=[0,1,2,3,4]
tf.one_hot(li,depth=5,on_value="HII",off_value="0")

<tf.Tensor: shape=(5, 5), dtype=string, numpy=
array([[b'HII', b'0', b'0', b'0', b'0'],
       [b'0', b'HII', b'0', b'0', b'0'],
       [b'0', b'0', b'HII', b'0', b'0'],
       [b'0', b'0', b'0', b'HII', b'0'],
       [b'0', b'0', b'0', b'0', b'HII']], dtype=object)>

In [61]:
#sqaring  new tensor
H=tf.range(1,10)

In [62]:
tf.math.sqrt(tf.cast(H,dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.2360678, 2.4494896,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [63]:
tf.math.log(tf.cast(H,dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

In [64]:
num=np.array([1,2,3,5])

In [65]:
tense=tf.Variable(num,dtype=tf.float32)

In [66]:
tense

<tf.Variable 'Variable:0' shape=(4,) dtype=float32, numpy=array([1., 2., 3., 5.], dtype=float32)>

In [67]:
tf.constant([[[2,4],[2,4]]])

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[2, 4],
        [2, 4]]], dtype=int32)>

In [68]:
tf.config.list_physical_devices("GPU")

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [69]:
!nvidia-smi

Wed Mar 13 15:48:27 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   41C    P0              27W /  70W |    107MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--